### ISSUE TITLE
Ability to enable / disable passphrase for connected device

### ISSUE THREAD

**Issue by t4777sd** [trezor/python-trezor#101]
Trezor has a security issue where it advertises the use of a 25th seed as documented here: https://www.reddit.com/r/TREZOR/comments/5vln7d/security_issue_with_25th_seed_word_passsphrase/

The only known workaround is to disable / enable the advertising of the 25th seed use manually. The only way to do this is via mytrezor.com, which is yet another security issue as mytrezor could be logging access requests to the server.

As such, until this bug is resolved, there should be an option in trezorctrl to easily disable / enable the passphrase advertising feature so users are not forced to compromise security by going to mytrezor.

**Comment by prusnak** [comment]
Added `trezorctl disable_passphrase` and `trezorctl enable_passphrase` commands.

Available in `trezorctl` provided by python-trezor >= 0.7.12
