### ISSUE TITLE
Looking for an offline tool to restore / change the seed words

### ISSUE THREAD

**Issue by Voluntary-zcash** [trezor/python-trezor#114]
https://doc.satoshilabs.com/trezor-user/settingup.html links to this github page for offline python tools.  I've followed the https://github.com/trezor/python-trezor/blob/master/README.rst instructions and it seemed to install without issue.  Now what?  Is there and proper readme or guide?  Where is it?

**Comment by prusnak** [comment]
It's the same like any other command line tool:

`trezorctl --help` - to list commands
`trezorctl command --help` - to get help on command, for example `trezorctl recovery_device`

**Comment by prusnak** [comment]
If you want "proper guide" you are welcome to write it. I make sure to include it in our documentation.

**Comment by saleemrashid** [comment]
The example should probably briefly mention the `trezorctl` command (so users know of its existence)

**Comment by prusnak** [comment]
Added `trezorctl` to README in https://github.com/trezor/python-trezor/commit/348db517758af8b3ad926629b669f92274b6cacb

That said, anyone is welcome to add stuff to documentation
