### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by Quentin-M** [trezor/python-trezor#116]
Thanks for writing and having this tool open-sourced.

Using MyEtherWallet as a client to TREZOR to manage Ethereum is a pretty poor experience for several reasons. First of all, it requires to have a Chrome extension. Then, wallet.trezor.io must be functioning properly, as well as myetherwallet.com (except if you want to run a TLS server for an HTML page). And finally, the UX is not great/confusing.

I do not really want to deal with _trezor-chrome-extension_, _connect.js_, _trezor.js_, any similar JS-based application, or run a daemon such as _trezord_ to simply be able to manage an USB device and sign transactions either. It seems overkill. Additionally, it does not seem like the repositories are too active..

At least, this Python client is pretty clear, fairly low-level, is quite contained and dependency free!
I feel like there is a strong need for a solid CLI client for TREZOR AND Ethereum.

**Comment by prusnak** [comment]
I agree in all points. I would love to accept more pull requests in python-trezor. I bet this also applies to MEW guys.
