### ISSUE TITLE
Include the git commit from what protobuf code is generated from

### ISSUE THREAD

**Issue by hegjon** [trezor/python-trezor#117]
There are no information what commit the protobuf messages are compiled from, this makes it hard to rebuild the the correct protobuf messages from source.

Sugestion, include something like this in build_pb.sh
`git rev-parse HEAD > $CURDIR/.trezor-protob-version.txt`

**Comment by prusnak** [comment]
Great idea! https://github.com/trezor/python-trezor/commit/f880a09ae79c603dd8aa0dc54ec02298b202d50d

**Comment by hegjon** [comment]
Thanks, I liked the way you solved it
