### ISSUE TITLE
sudo pip install trezor_agent fails to compile

### ISSUE THREAD

**Issue by PavelNiedoba** [trezor/python-trezor#127]
I assume trezor_agent is part of this repo, I'm trying to follow install guide

[compilation.err.txt](https://github.com/trezor/python-trezor/files/1224979/compilation.err.txt)
tmp/comp.err

i asked question on https://stackoverflow.com/questions/45692279/using-bitcoin-trezors-ssh-agent too

**Comment by saleemrashid** [comment]
@PavelNiedoba The correct repository is romanz/trezor-agent

**Comment by PavelNiedoba** [comment]
Moved it there ...
