### ISSUE TITLE
ethereum_get_address different from MyEtherWallet

### ISSUE THREAD

**Issue by ulope** [trezor/python-trezor#129]
(I'm not sure if this is the correct repo to report this but since I'm seeing this issue from the python client it seemed like a good starting point.)

The ethereum address returned by `trezorctl ethereum_get_address` differs from the addresses MyEtherWallet shows when using the Trezor. I assume different methods to derive the key (and thereby address) are being used. It would be nice if there would be a way to get the same addresses MEW uses from the python client.

**Comment by prusnak** [comment]
How exactly do you use `trezorctl ethereum_get_address`? Do you specify correct path?

**Comment by ulope** [comment]
Thats the exact command I'm using. I'm not manually specifying a path.

**Comment by prusnak** [comment]
You need to use the following to generate first address of first account:

```
trezorctl ethereum_get_address -n "m/44'/60'/0'/0/0"
```

**Comment by ulope** [comment]
Good to know. Maybe that should be mentioned in the commands help.
