### ISSUE TITLE
Portable binary releases?

### ISSUE THREAD

**Issue by jonathancross** [trezor/python-trezor#143]
`trezorctl` seems like a great tool for interacting with the Trezor on an air-gapped system (to prevent keyloggers from capturing passphrase) -- for example on Tails.  Unfortunately the dependencies are rather extensive making this challenging to build and use on an offline system.  A signed, portable binary would make this much less painful for users.  :-)

**Comment by prusnak** [comment]
Tails contains python-trezor and thus trezorctl by extension in its
default system.
I prefer using proven solution such as Tails to people brewing their own
solutions with binaries (although signed) provided by me.

**Comment by jonathancross** [comment]
> Tails contains python-trezor and thus trezorctl by extension in its
default system.

Thats fantastic, apologies for not checking first.  Cheers!
