### ISSUE TITLE
script-type: "segwit": Failure: Can't encode address

### ISSUE THREAD

**Issue by jonathancross** [trezor/python-trezor#144]
Am I using this incorrectly?
```
trezorctl get_address -c Bitcoin -t segwit -n "m/49'/0'/0'/0/0"
Failure: Can't encode address
```

**Comment by prusnak** [comment]
Are you using trezorctl from master or from PyPI?

**Comment by saleemrashid** [comment]
Firmware supporting Bech32 has not yet been released, you probably want `-t p2shsegwit`

**Comment by jonathancross** [comment]
> Are you using trezorctl from master or from PyPI?

I just decompressed latest release (v0.7.16) on Tails 3.0 and ran `trezorctl` from there.  Seems that is very old code.  Perhaps we can get a new release tagged?

> Firmware supporting native SegWit has not yet been released...

Thanks, maybe a better error message could be presented to the user?

>  you probably want -t p2shsegwit...

I'm just exploring what works and doesn't work so I can provide examples in `USAGE.rst`.

**Comment by MelbourneDeveloper** [comment]
I'm getting this error when talking via HID. I am sending the GetAddress message, and if I specify the Multisig part with a public key, I get the error message Can't encode address'. I can't only get the Address if I do not specify Multisig

**Comment by MelbourneDeveloper** [comment]
This is the code:

 char address[MAX_ADDR_SIZE];
 layoutProgress(_("Computing address"), 0);
 if (!compute_address(coin, msg->script_type, node, msg->has_multisig, &msg->multisig, address)) {
fsm_sendFailure(FailureType_Failure_DataError, _("Can't encode address"));

https://fireproxy.crushus.com/github.com/trezor/trezor-mcu/blob/master/firmware/fsm.c

But, it doesn't give me any clues on what is wrong:

**Comment by saleemrashid** [comment]
@MelbourneDeveloper Could you post the `GetAddress` call you are making?
