### ISSUE TITLE
Invalid Pin when using encfs_aes_getpass.py

### ISSUE THREAD

**Issue by ddworken** [trezor/python-trezor#15]
When I try to run encfs_aes_getpass.py, I get past it asking for a label for the new drive, and prompting the trezor device for entropy. It then asks me to "Please enter old PIN: " while the Trezor screen says "Please enter current PIN:". It is here that I am confused about how to enter my pin. If my password is 1234 and the trezor is displaying: 

| 2 | 8 | 3 |
| --- | --- | --- |
| 5 | 4 | 6 |
| 7 | 9 | 1 |

Which of these options would I enter? 
1. 9135
2. 2835

I have tried both of the above methods, and both give me an Invalid PIN exception.

**Comment by tphyahoo** [comment]
From a usability perspective, this is really confusing. 

Would you consider outputting the numeric keyboard layout to help the user, when in text mode?

So to be pedantically concrete, when you run helloworld.py the message would be something like

"Passphrase required: 
(numeric keypad default layout is: 
789
456
123)"

I think this would help usability a lot.

**Comment by prusnak** [comment]
Feel free to suggest a change via a pull request.

**Comment by prusnak** [comment]
Implemented in b2bc5092189c174735f70e1cad0b68e461b40e42
