### ISSUE TITLE
test_multisig_change failures

### ISSUE THREAD

**Issue by prusnak** [trezor/python-trezor#154]
Currently all device tests pass except

```
test_multisig_change.py .FFFF...
:
TestMultisigChange.test_external_internal
TestMultisigChange.test_internal_external
TestMultisigChange.test_multisig_change_match_first
TestMultisigChange.test_multisig_change_match_second
```

All failures are related to an extra `ButtonRequest_ConfirmOutput` from the device.

@jhoenicke Can you please confirm that this new behavior is correct?

**Comment by teknico** [comment]
I'm also seeing three similar failures in `test_msg_signtx.py`:
- `TestMsgSigntx.test_one_three_fee`
- `TestMsgSigntx.test_testnet_fee_too_high`
- `TestMsgSigntx.test_two_two`

They all expect `ButtonRequest_ConfirmOutput` but get something else, so they seem related.

(`test_multisig_change.py` is currently skipped in `trezor-core/tests/run_tests_device.sh`, among others.)

**Comment by jhoenicke** [comment]
@teknico Looks like I forgot to add the pull-request for `test_msg_signtx.py`.  Just added it.

I thought I had all tests going through at some time, but I'll recheck later.  Maybe I forgot to run the multisig tests.

**Comment by teknico** [comment]
You actually didn't forget: #155 is the same PR as #138, and is already merged to `master`.

**Comment by jhoenicke** [comment]
I have created some multisig wallets on testnet (with electrum) and funded them, so I can write new tests.

(If you find them, please leave my testcoins there :)

**Comment by prusnak** [comment]
@teknico Failures you see are there because you don't use firmware from master. I specifically changed those tests to follow the new behaviour (confirm of OP_RETURN on display).

**Comment by teknico** [comment]
@prusnak, good to know, thanks. How do I do that?

**Comment by prusnak** [comment]
https://github.com/trezor/trezor-mcu#how-to-build-trezor-firmware

But be careful, the firmware is unsigned and thus will remove the storage, so use it only if you have a spare device.

**Comment by teknico** [comment]
I'm using the v2 emulator running `make emu` and `make test_emu` in `trezor-core`. Any way to use the master firmware there?

**Comment by prusnak** [comment]
No, this is about firmware for v1.

**Comment by teknico** [comment]
So no way to run the device tests with the v2 emulator currently?

**Comment by prusnak** [comment]
No, not everything is implemented in v2. See https://github.com/trezor/trezor-core/blob/master/tests/run_tests_device.sh to learn which tests are being skipped now.

**Comment by teknico** [comment]
Right. Then I guess `test_msg_signtx.py` should be skipped too, because of the three failures mentioned above.
