### ISSUE TITLE
error with pip3 install trezor (pyx)

### ISSUE THREAD

**Issue by thob** [trezor/python-trezor#157]
`error: unknown file type '.pyx' (from 'hid.pyx')`

`
`----------------------------------------
Cleaning up...
Command /usr/bin/python3 -c "import setuptools, tokenize;__file__='/tmp/pip_build_root/hidapi/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-hip0dwkp-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip_build_root/hidapi
Storing debug log for failure in /root/.pip/pip.log

also getting this
```trezorctl get_features
Traceback (most recent call last):
  File "/usr/local/bin/trezorctl", line 618, in <module>
    main()
  File "/usr/local/bin/trezorctl", line 595, in main
    transport = get_transport(args.transport, args.path)
  File "/usr/local/bin/trezorctl", line 85, in get_transport
    from trezorlib.transport_hid import HidTransport
  File "/usr/local/lib/python3.4/dist-packages/trezorlib/transport_hid.py", line 22, in <module>
    import hid
ImportError: No module named 'hid'```

Any idea?

**Comment by prusnak** [comment]
Update your setuptools package.
