### ISSUE TITLE
Please tag a new release

### ISSUE THREAD

**Issue by jonathancross** [trezor/python-trezor#158]
The latest release (`v0.7.16`) is very old and is missing a tremendous amount of functionality / bug fixes (eg. #146).  Would be great to get a new release tagged, especially now that Bech32 segwit addresses are available.

On a side note: would also be good to have releases signed so we know the devs actually approved and stand behind that release.

**Comment by jonathancross** [comment]
Now that v1.6 is released and we can use native SegWit addresses, would be fantastic to get a new release tagged with all this great new functionality.

**Comment by jonathancross** [comment]
@prusnak @slush0 Anything blocking tagging of a new release?
I'd really love to get Tails OS updated with the latest `trezorctl` which can sign transactions.  :-)

**Comment by prusnak** [comment]
Slush is working an porting Electrum 3 code to work with 0.8.x. Once this is done and we know there are no further changes required to python-trezor, we can tag the 0.8.x release.

**Comment by jonathancross** [comment]
Thank you for the update. Really hope something can be tagged soon as `master` branch is so much more functional than current version in debian repo.

**Comment by jonathancross** [comment]
I just discovered that the [debian version is from 2016](https://packages.debian.org/en/stretch/python-trezor) and is blocked from ugrade by [this bug](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=884417)... so I guess there is multiple issues with getting latest version into TailsOS.  I'll reach out to @ulrichard who seems to be the maintainer.  Maybe we can get the debian side fixed by the time a new release is tagged  :-)

**Comment by prusnak** [comment]
Just tagged `0.9.0` release: https://github.com/trezor/python-trezor/releases

Also published at PyPI: https://pypi.python.org/pypi/trezor

**Comment by jonathancross** [comment]
Fantastic! I'll see if I can help get `v0.9.0` into debian.
