### ISSUE TITLE
[feature request] Add version number to trezorctl --help 

### ISSUE THREAD

**Issue by jonathancross** [trezor/python-trezor#159]
The version of `trezorctl` that is installed with Tails is very old.  This was not immediately obvious to me because there is no version number shown in the help. Example of desired output:

    Commandline tool for TREZOR devices.
    Version: v0.7.16

**Comment by prusnak** [comment]
`trezorctl version` now responds with the python-trezor version

**Comment by jonathancross** [comment]
Thanks! Any chance we can get the GitHub release version number in here as well?
From a user standpoint, I'd be more interested in knowing which version of `trezorctl` I have (eg on Tails OS) - that way I can check if it has the capabilities I need.

**Comment by prusnak** [comment]
Not sure I understand.

What exactly would you like to see as the output of version command?

**Comment by jonathancross** [comment]
Something like this would be great:

    Commandline tool for TREZOR devices.
    Release: v0.7.16
    Trezorlib: v0.8.0a3

`Release` version corresponds to the latest tagged release: https://github.com/trezor/python-trezor/releases ... Ideally new releases would be tagged more often (requested in #158).

For version in `master`, could just use git commit:

    Commandline tool for TREZOR devices.
    Release: master@4583573
    Trezorlib: v0.8.0a3

**Comment by prusnak** [comment]
Both trezorlib and trezorctl version numbers should be same at all times, so it does not make sense to print them twice. Git version is rather tricky, so let's leave that out for now.

**Comment by jonathancross** [comment]
Ah, okay, I thought they were totally separate because the git release number is currently so different.
