### ISSUE TITLE
Link to USAGE.rst more visibly in README.rst

### ISSUE THREAD

**Issue by saleemrashid** [trezor/python-trezor#166]
I wasn't even aware of the existence of this file :smile:

Currently the only link from the README is very easy to miss.

> or visit usage page for more info.

/cc @jonathancross

**Comment by jonathancross** [comment]
Yeah, it is a bit hard to find in the README. I'll send a PR after #165 is merged (that one is already getting a bit big).

**Comment by prusnak** [comment]
Fixed via #168
