### ISSUE TITLE
Encfs script returns different password in tagged/published version than on master

### ISSUE THREAD

**Issue by karel-3d** [trezor/python-trezor#169]
I am using encfs script from here to encrypt my backups

https://github.com/trezor/python-trezor/blob/master/tools/encfs_aes_getpass.py

When using version from master, encfs shows error about wrong password (on a file encrypted by the older, previously installed version, from python repository). When using version from latest tag, it works. I did not investigate further cause of the issue.

**Comment by jonathancross** [comment]
Hi Karel, was nice to meet you briefly at 34C3.
Would be good to have the exact error message for this. 
Seems that this script writes the encrypted password to [password.dat](https://github.com/trezor/python-trezor/blob/master/tools/encfs_aes_getpass.py#L87) file, so you can check if that file exists, then compare the values being returned from the Trezor in the 2 different versions of the library.

**Comment by karel-3d** [comment]
Sorry for late reply.

Hm. Master fails, on new volume, with this
```
Traceback (most recent call last):
  File "/home/g/dev/python-trezor/tools/encfs_aes_getpass.py", line 128, in <module>
    main()
  File "/home/g/dev/python-trezor/tools/encfs_aes_getpass.py", line 113, in main
    json.dump(data, open(passw_file, 'wb'))
  File "/usr/lib/python3.6/json/__init__.py", line 180, in dump
    fp.write(chunk)
TypeError: a bytes-like object is required, not 'str'
fatal: zero-length passwords are not allowed
```

v0.7.16 (newest tagged at the time of writing this issue) fails with
```
Traceback (most recent call last):
  File "/home/g/dev/python-trezor/tools/encfs_aes_getpass.py", line 18, in <module>
    from trezorlib.client import TrezorClient
ImportError: No module named trezorlib.client
fatal: zero-length passwords are not allowed
```
But that might be because I have new version already installed.

But when I install old python-trezor version with pip2, I get the same error.

And when I just run `python2` repl, I get this

```
python2
Python 2.7.14 (default, Sep 23 2017, 22:06:14) 
[GCC 7.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from trezorlib.client import TrezorClient
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "trezorlib/client.py", line 31, in <module>
    from mnemonic import Mnemonic
ImportError: No module named mnemonic
>>> 
```

**Comment by karel-3d** [comment]
Hm, not sure how to install module mnemonic for python2.

pip2 says

```
Requirement already satisfied: mnemonic in /usr/local/lib/python3.6/dist-packages
Requirement already satisfied: pbkdf2 in /usr/local/lib/python3.6/dist-packages (from mnemonic)
```

even when I specifically install with pip2. However python2 then does not see the packages.

**Comment by matejcik** [comment]
a missing requirement? try `pip2 install mnemonic`

**Comment by karel-3d** [comment]
I did, but pip2 kept on installing things just for python3 :( I needed to force-reinstall pip2.

Anyway, everything started working (even the original issue), when I forcibly rewrote the first line of  `tools/encfs_aes_getpass.py` from `python3` to `python2`, and I installed everything under python2 and not python3.

**Comment by karel-3d** [comment]
I can confirm. With existing encfs volumes encrypted with the script, python2 (with 0.9.0) works and python3 doesn't and says `Error decoding volume key, password incorrect`

With new volumes, python3 is not able to create them.

To reproduce:

`encfs --standard --extpass=/path/to/python-trezor/tools/encfs_aes_getpass.py /path/to/encrypted /path/to/decrypted`

encfs is in apt, although it shows this ugly warning on instal

![screenshot from 2018-04-15 16-18-28](https://user-images.githubusercontent.com/104945/38781419-6dcb4f90-40e4-11e8-8a52-24b18f528ef2.png)

**Comment by matejcik** [comment]
fixed in 688fe06

**Comment by karel-3d** [comment]
Hm. I tried it now and it shows "password incorrect", with current master and latest pip version.

I will try to hunt down the bug again.

**Comment by karel-3d** [comment]
When I

* downgrade trezor in pip to 0.9.0
* get 0.9.0 in python-trezor
* use trezor 1
* change python from python3 to python2 in the encfs tools

... it works. When I use everyhing from master and latest pip, it breaks

**Comment by karel-3d** [comment]
Please reopen. I cannot find where the issue is since I don't really understand all the python2/python3/bytes/hex thing

**Comment by matejcik** [comment]
encfs script is again fixed in master, and contains a library version guard that should ensure that people don't mix-and-match
