### ISSUE TITLE
Unable to install in macOS High Sierra due to SIP

### ISSUE THREAD

**Issue by jsnod** [trezor/python-trezor#185]
I was unable to get python-trezor running in macOS following the install instructions in README.  Updating setuptools would fail with an `Operation not permitted`:

```
Error: [('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/markers.pyc', '/tmp/pip-LBM_rt-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/markers.pyc', "[Errno 1] Operation not permitted: '/tmp/pip-LBM_rt-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/markers.pyc'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/__init__.py', '/tmp/pip-LBM_rt-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/__init__.py', "[Errno 1] Operation not permitted: '/tmp/pip-LBM_rt-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/__init__.py'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/markers.py', '/tmp/pip-LBM_rt-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/markers.py', "[Errno 1] Operation not permitted: '/tmp/pip-LBM_rt-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/markers.py'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/__init__.pyc', '/tmp/pip-LBM_rt-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/__init__.pyc', "[Errno 1] Operation not permitted: '/tmp/pip-LBM_rt-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/__init__.pyc'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib', '/tmp/pip-LBM_rt-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib', "[Errno 1] Operation not permitted: '/tmp/pip-LBM_rt-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib'")]
```

Apparently this is due to System Integrity Protection (SIP) that was added in El Capitan.  I was able to get around this by passing in the `--user` flag to the PIP commands to install into my user environment rather than the system environment:

```
pip install setuptools --user
pip install -r requirements.txt --user
pip install trezor --user
```

Unfortunately this installs `trezorcrl` into `/Users/<user>/Library/Python/2.7/bin/trezorctl`, so you must either add the dir to your `$PATH` or manually enter the full path to run `trezorctl`

I would submit a pull request to reflect this in the README but I'm not sure if this is the best way forward.  Thoughts?

**Comment by saleemrashid** [comment]
Not sure if adding system specific information in the `README` is very helpful. Advanced users will understand the implications of the `pip` command (and know when to add `--user` and if they need to have the folder in their `$PATH`).

On the other hand, I believe that inexperienced users should do a bit of personal research rather than rely solely on the instructions provided by the `README` (as they will be able to find information relevant to their situation). So perhaps a link to https://packaging.python.org/tutorials/installing-packages/ might be the best solution.

**Comment by prusnak** [comment]
Not sure what are the best practices for macOS, but how is it with
Python 3? Is that protected as well? If we are to add system specific
instructions I would be happier if it described Python 3 not Python 2
stuff in case we'll drop the Py2 compatibility in the future.

**Comment by saleemrashid** [comment]
@prusnak The system protection just means that you cannot write to system directories (e.g. you cannot use `pip install` without `--user`).

But it's the same situation as a user trying to follow the `README` on a Linux system without `root`. They cannot write to `/usr` and it would fail.

**Comment by jsnod** [comment]
The difference being that on MacOS, it fails even when running as root.  SIP prevents even root from modifying the system Python libraries.

**Comment by darwin** [comment]
I would suggest user to use Homebrew and avoid system python for development, they can `brew install python` or `brew install python3` and delegate to their instructions which will likely be maintained and up-to-date.

https://docs.brew.sh/Homebrew-and-Python.html

**Comment by darwin** [comment]
Also drop `sudo -H` from the readme's `pip install` lines. People should know if they have to use sudo or not depending on their system. And if they don't, they don't harm their python installation.

More specifically:
1) if they use system python, they get a permission error without sudo, so they can try it again with sudo (after googling maybe)
2) if they use non-system python, it would silently create a messy situation and execute pip install with sudo littering their user-locations with admin files

btw. Just for record. I just tested the `pip install` steps from readme with my homebrew'ed Python2 and Python3 and both seem to work (at least all got installed and both `trezorctl --help` and `python3 trezorctl --help` work as expected)

```
> sw_vers
ProductName:	Mac OS X
ProductVersion:	10.13.3
BuildVersion:	17D25b

> python --version
Python 2.7.14

> python3 --version
Python 3.6.4
```

**Comment by prusnak** [comment]
@matejcik please review whether dropping `sudo -H` from the documentation is a good idea. not sure what else we can do here, so please close this issue after your decision.

**Comment by matejcik** [comment]
(yes, I totally wanted to be notified three times from my playground repo. thanks github.)
anyway, this commit drops the `sudo -H`, and also updates the instructions for 0.9.2
