### ISSUE TITLE
Fix trezorctl print_result function

### ISSUE THREAD

**Issue by prusnak** [trezor/python-trezor#199]
`print_result` function behaved much better when  old protobuf messages were used. Now two issues need fixing:

a) json output does not work for protobuf messages (test by `trezorctl -j get_features`)

b) normal output is confusing and could use more formatting love (test by `trezorctl get_features`)

I would rather modify the `print_function`  and not modify the `protobuf.MessageType` to avoid any extra dependencies nor complex code in `trezorlib/protobuf.py`

**Comment by matejcik** [comment]
#222 fixes this.

what is the JSON output for? is it used anywhere?

**Comment by matejcik** [comment]
fixed in v0.9.1
