### ISSUE TITLE
Bad signature produced by trezorctl

### ISSUE THREAD

**Issue by jakubtrnka** [trezor/python-trezor#204]
I tried to do atomic cleanup of some trezor accounts - including both legacy and p2shsegwit. When I wanted to broadcast transaction via 'bitcoin-cli sendrawtransaction', I recieved message
```
error code: -26
error message:
64: non-mandatory-script-verify-flag (Signature must be zero for failed CHECK(MULTI)SIG operation)
```
Which probably signalize bad signature.
Raw transaction on which it failed is  [here](https://chainanalytics.net/transakce.txn.asc) (encrypted for P. Rusnak PGP public key)

I checked twice whether I used correct derivation paths in `trezorctl sign_tx` dialog.

**Comment by prusnak** [comment]
What version of `bitcoind` and `bitcoin-cli` are you using?

**Comment by jakubtrnka** [comment]
This was about one week old build on git master (v0.15.99.0-898f560b5).

**Comment by jakubtrnka** [comment]
First thing that came into my mind was some problem with repeated hashing when combining Segwit and Legacy UTXO. Legacy transaction require quadratic hashing, Segwit linear. But if that's the case I don't know how to check that. I never really understood this problematic.

**Comment by jakubtrnka** [comment]
First thing that came into my mind was some problem with repeated hashing when combining Segwit and Legacy UTXO. Legacy transaction require quadratic hashing, Segwit linear, afaik. I don't know, however, how to check that quickly. I never really understood this problematic.

**Comment by jonathancross** [comment]
Has this been resolved or is there new info?

**Comment by matejcik** [comment]
I don't think we ever managed to reproduce this problem.

I'm going to close the report, because it's quite old and I'm honestly not sure what to do with it. Please reopen if this is still happening, or if you have a clearer idea about what to look for.
