### ISSUE TITLE
Dry run test seed, can't correct bad words.

### ISSUE THREAD

**Issue by beekingo** [trezor/python-trezor#207]
Hello!

I do the dry run to test if the seed i noted was right with this command:

`trezorctl recovery_device -d -w 24 -t matrix`

I do it dozen of times until i got it right. For some reason i was unable to correct a word if i made a mistake. On screen help says i can correct with backspace but it didn't work.

I tried this on a Windows 10 computer. 

Thanks!

**Comment by jonathancross** [comment]
Do you mean that you typed part of a word, then hit _**backspace**_ and the last letter was not deleted?
Of did you type the _**enter**_ key and then try to fo back? (this does not work)

**Comment by beekingo** [comment]
Hello Jonathan, none of that two options works on my computer. I have a latin american keyboard layout, don't know if that can me an issue. 

Thanks

**Comment by matejcik** [comment]
Confirmed, backspace was broken on Windows.
(btw even going back to the previous word works :) )

fixed, thanks for the report!
