### ISSUE TITLE
Error when importing libusb1 on Windows

### ISSUE THREAD

**Issue by bauerj** [trezor/python-trezor#218]
Using 0.9.0 on Windows yields this error:

```python-traceback
 bauerj@DESKTOP-5KP26RC  ~  python
Python 3.6.2 (v3.6.2:5fd33b5, Jul  8 2017, 04:14:34) [MSC v.1900 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from trezorlib.device import TrezorDevice
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\python3.6.2\lib\site-packages\trezorlib\device.py", line 23, in <module>
    from .transport_webusb import WebUsbTransport
  File "c:\python3.6.2\lib\site-packages\trezorlib\transport_webusb.py", line 24, in <module>
    import usb1
  File "c:\python3.6.2\lib\site-packages\usb1\__init__.py", line 61, in <module>
    from . import libusb1
  File "c:\python3.6.2\lib\site-packages\usb1\libusb1.py", line 199, in <module>
    libusb = _loadLibrary()
  File "c:\python3.6.2\lib\site-packages\usb1\libusb1.py", line 173, in _loadLibrary
    return dll_loader('libusb-1.0' + suffix, **loader_kw)
  File "c:\python3.6.2\lib\ctypes\__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found
```

**Comment by prusnak** [comment]
That is a result of non-working installation of python-libusb1 dependency. Please see the following issue for resolution: https://github.com/vpelletier/python-libusb1/issues/7

**Comment by bauerj** [comment]
Does it mean that `pip` installs a broken version of python-libusb1 *by default* or that this is merely an issue with my installation?

**Comment by prusnak** [comment]
I guess that python-libusb1 does not install the required libusb-1.0 dll by default, but best would be to ask in the linked issue.

**Comment by bauerj** [comment]
I think that is correct. In that case, wouldn't it make sense to add that to the installation instructions for python-trezor?

**Comment by prusnak** [comment]
I agree, but let's first find out what to put there ...

**Comment by bauerj** [comment]
For me, the following worked:

1. Download `libusb-1.0.21.7z`
2. Copy `MS{32,64}\dll\libusb-1.0.dll` to the location of your `python.exe`
