### ISSUE TITLE
Share account between trezor and hw1

### ISSUE THREAD

**Issue by ulrichard** [trezor/python-trezor#22]
Is it possible to share a trezor account with hw1?
Say I have a trezor with account#1 and account#2 and I want to share the account#2 with HW1.
How would I get the seed that I need to initialize the HW1?
I know pycoin has some key derivation functions exposed, but I don't know how much format conversion is needed at different steps.

**Comment by prusnak** [comment]
Closing. Solution described in the referenced issue above.
