### ISSUE TITLE
Unlock LUKS device during boot (initramfs) using Trezor

### ISSUE THREAD

**Issue by pruflyos** [trezor/python-trezor#231]
I would like to use the Trezor to unlock a LUKS encrpyted root partition of a system during early boot (initramfs). `trezorctl decrypt_keyvalue` would be perfect for that, the only problem is it requires Python, which is not available in initramfs and I would like to avoid building an initramfs containing Python just for trezorctl.

Is there any other C based library / command line tool to communicate with the Trezor? Or is it possible to cross compile trezorctl into a static C file?

I really like how U2F (Universal Two Factor Authentication) is exposed as a kernel device, so no Python is required, but unfortunately U2F can't be used to decrypt a specific value.

**Comment by prusnak** [comment]
There is no dedicated C library, but it should be really straightforward to create one.

You should be able to use U2F token such as TREZOR with LUKS. I would love to see someone explore this area:

https://github.com/agherzan/yubikey-full-disk-encryption

https://github.com/cornelinux/yubikey-luks

**Comment by pruflyos** [comment]
The problem with `Trezor & U2F mode` is that it doesn't ask for the `pin & password` as in `normal mode` (e.g. SSH or GPG via trezor-agent). So it is useful as a `2nd factor` device, but not so secure if used as the device to unlock the LUKS container. If somebody get's a hold on the Trezor, he/she could unlock the LUKS device instantly.

**Comment by prusnak** [comment]
1) how is that different from other U2F tokens?

2) TREZOR model T asks for PIN on its screen before USB connection is even enabled

**Comment by pruflyos** [comment]
> 1. how is that different from other U2F tokens?

Don't know. Trezor One is the only U2F token I used so far... 

I see that there's a Yubikey solution for LUKS. I'm just saying that the described `Challenge only mode (1FA)` has security drawbacks which might not be acceptable for all LUKS users.
The `Challenge + password mode (2FA)` seems to be a lot more secure, but has the drawback that the password has to be entered on the `host system` (initramfs), which might be `semi-trusted`. I'm only refering to the initramfs as `semi-trusted`, whereas the encrypted root system can be considered `trusted`.
Ideally, the password is entered on a secure (trusted) device like the Model T instead of the keyboard in the `semi-trusted` initramfs system. The resulting LUKS secret is then piped directly to the unlocking script and as hard as possible to intercept (man in the middle attack). I know this doesn't provide ultimate security as with a `signed initramfs` system. However, many systems don't have a `secure boot` mechanism yet, so the envisioned approach (LUKS encrypted root) might be an acceptable compromise/interrim solution.

> 2. TREZOR model T asks for PIN on its screen before USB connection is even enabled

Nice! That should be as close as we can get without `secure boot`. The only question is if `the challenge` can be the same for every attempt? AFAIK the Trezor has a counter which is increased every time, right? But for LUKS, we need a symmetric key so when using U2F, the Trezor response needs to be the same each time... basically the U2F response is the symmetric key to unlock the LUKS container.

**Comment by pruflyos** [comment]
This thread model analysis of the Yubikey approach is an interesting read:
https://github.com/cornelinux/yubikey-luks/issues/1#issuecomment-326504799

I guess a device like the `Trezor Model T` which has a Micro-SD slot could be used to move the LUKS-Header off the target device onto the SD-Card of `Model T`. This way you could decrypt the whole header using GPG in the initramfs and unlock the LUKS-Body. Certain types of "evil-maid attack" would be very hard this way.

This comment mentions an "Aegis" device, which sounds similar to the capabilities of the `Model T`:
https://github.com/cornelinux/yubikey-luks/issues/1#issuecomment-366189913

**Comment by saleemrashid** [comment]
@pruflyos Bear in mind that, without Secure Boot, keeping the initramfs on the computer will always be the point of failure. It can modify the rootfs after the TREZOR gives up the symmetric encryption key.

**Comment by pruflyos** [comment]
@saleemrashid Sure. GPG-verifying and booting the initramfs from the `Model T's SD-Card` would be optimal for `non-Secure Boot` systems.

**Comment by pruflyos** [comment]
This is the `Aegis USB Key`: https://www.apricorn.com/flash-keys/aegis-secure-key-3z
I bet the `Model T` could accomplish the same purpose & security.

**Comment by pruflyos** [comment]
What about the following approach for a non-Secure Boot system?

Verify the the initramfs manually using the `Model T` each time before you boot the system and unlock the root partition.
a) If the target system boots from a Micro-SD card anyway (e.g. Raspberry Pi), just put that card into the `Model T's slot` first and verify the signature of the initramfs before actually booting from it. Isn't the `Model T` supposed to run "custom" apps in the future? This could be a small app, that verifies the signature of an initramfs.
b) If the target system boots from any other type of disk, you can manually verify the initramfs using the Trezor externally. E.g. plugging the disk to a system you trust or booting it from a Live-CD/USB first to verify the initramfs using GPG.

Of course this manual verification is only necessary when you have left the target system in an unstrusted environment and need to reboot. (e.g. power outage or kernel updates that require a reboot).

**Comment by matejcik** [comment]
ISTM you're using the wrong tools for the job. Your usecases are better solved simply by booting off a USB stick that you carry on your person.

**Comment by matejcik** [comment]
I'm going to close this issue as it is not relevant to the python-trezor library anymore.
I'm not sure if there's a good forum for this general idea - maybe the Trezor subreddit?

**Comment by xaionaro** [comment]
> trezorctl decrypt_keyvalue would be perfect for that, the only problem is it requires Python, which is not available in initramfs and I would like to avoid building an initramfs containing Python just for trezorctl.

@pruflyos I don't know is that useful for you but if still actual you can use this: https://github.com/xaionaro-go/trezorLuks (it's a simple wrapper for "cryptsetup" on Go).

```
$ ldd ./trezorLuks
        not a dynamic executable
```
(you can just copy it into your `initrd`)
