### ISSUE TITLE
Separate "altcoin" features from trezor client library

### ISSUE THREAD

**Issue by matejcik** [trezor/python-trezor#239]
The client library is, decidedly and deliberately, not a wallet. In itself, it only "supports coins" as far as the signing calls are distinct; speaking in terms of the API, it would be even better if distinct coins could call the same `sign_tx` method and differentiate based on the transaction properties.

However, there are a couple features in the library that need explicit "coin support".

One is the `TxApi`, an interface for downloading transactions off some sort of backend. This is necessary for signing Bitcoin-like transactions, where Trezor needs to inspect transaction inputs. The reason for this is presumably convenience of `trezorctl` users; if this was not present, you'd have to specify manually each preceding transaction.
Another is `coins_slip44`, which assigns IDs to altcoins so that you can write address `"m/Dogecoin/0/0/1"` instead of the more verbose BIP44 format `"m/44'/3/0/0/1"`.

Neither of those things is required for a functioning Trezor interface. I'm opening this issue in order to track removal of these features from the core.

**Comment by matejcik** [comment]
The current plan is first to modify signature of `sign_tx` method so that it takes preceding transactions as an argument. Then the current `TxApi` functionality could be moved either to `trezorctl` directly, to support ease of use, or `trezorctl` could be modified to read transaction data in, say, JSON format instead of interactive input, and a separate tool would generate the JSON interactively using a backend.

Alternatively, we could make some sort of "micro-wallet" as a tool separate from `trezorctl` itself. This could handle user-friendly signing of transactions, enumerating UTXOs (#213) and possibly other features.

**Comment by matejcik** [comment]
Note that if `trezorctl` can sign JSON formatted transactions generated by a separate tool, this nicely facilitates offline signing.

**Comment by matejcik** [comment]
As for the `coins_slip44` database, I'm still unsure. It would be great if Trezor could return SLIP44 IDs for supported coins; otherwise, it's somewhat impractical to ship a database of coin IDs as part of the library. That's simply not the right place; OTOH it is a nice convenience feature.

In any case, the _SLIP44_ database should not rely on PRs for random coin support, as it is now. It should be generated, or perhaps loaded directly, from [coins.json](https://github.com/trezor/trezor-common/blob/master/coins.json) at the very least.

**Comment by matejcik** [comment]
related: #183 which wants the ability to sign "raw transactions". There is a [BIP174](https://github.com/bitcoin/bips/blob/master/bip-0174.mediawiki) describing the transaction format. This looks like a good basis for the serialized transaction format; perhaps we could implement a subset of this corresponding to currently supported features in Trezor - and make sure we reject transactions that go outside this subset.

**Comment by alepop** [comment]
About `coins_slip44`. Maybe is better to write something like this `Dogecoin/0/0/1` instead of `m/Dogecoin/0/0/1`. I think it even better, because `m` is constant.

**Comment by alepop** [comment]
@matejcik https://github.com/alepop/slip44-converter I've made something similar based on your idea.

**Comment by matejcik** [comment]
@alepop to be clear the address thing is not my idea, it was already a feature of trezorlib when I got it :) Both formats are possible actually, "m/Dogecoin/0/0/1" and "Dogecoin/0/0/1" both work in the current version.

My point here is that for proper translation of these addresses, you need a database of coin names and their SLIP44 IDs, and it's not clear at the moment how best to store/distribute that.

**Comment by alepop** [comment]
Maybe fetch constant data from the slip doc? like in this package https://github.com/bitcoinjs/bip44-constants/blob/master/update.sh, cache results locally and update it periodically. And address thing doesn't support coin symbol to get constants.

**Comment by matejcik** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [modify `sign_tx` signature to take preexisting transactions](https://trello.com/c/uP0Phgqk/2-modify-signtx-signature-to-take-preexisting-transactions)

**Comment by matejcik** [comment]
the slip44 part is now done (as PR #248)

**Comment by matejcik** [comment]
i would probably consider this done since c269d67cde313a2959e95281174d511a41fac3c7
with version 0.11.0 out, the `sign_tx` signature is changed in the appropriate way
