### ISSUE TITLE
Can't Communicate with USB

### ISSUE THREAD

**Issue by smartcharge** [trezor/python-trezor#243]
I have installed VirtualBox Version 5.2.6 r120293 (Qt5.6.2) and I have installed Ubuntu 16.04 LTS. I then installed the trezor according to the instruction at this website: https://github.com/trezor/python-trezor. I also attached the USB device to the VirtualBox and when I run "lsusb" in the terminal I can see the device "Satoshi Bitcoin Wallet [TREZOR]". But when I type the command "trezorctl get_features" into the terminal I get the following error:

File "usr/local/lib/python3.5/dist-packages/trezorlib/transport_hid.py", line 44, in open
      self.handle.open_path(self.path)
File "hid.pyx", line 72, in hid.device.open_path (hid.c:1682) 
OSError: open failed

I have no idea what this problem is.

**Comment by saleemrashid** [comment]
You probably don't have permission to access the device. Have you installed the udev rules?

**Comment by smartcharge** [comment]
I'm trying that now. But in the meantime I'm just using "sudo"

**Comment by prusnak** [comment]
Install udev rules from https://github.com/trezor/trezor-common/blob/master/udev/51-trezor.rules
