### ISSUE TITLE
Inform user about udev rules when opening device fails

### ISSUE THREAD

**Issue by saleemrashid** [trezor/python-trezor#244]
Add a non-intrusive (to avoid breaking downstream consumers of the library) warning that the user may not have udev rules installed when the device cannot be opened.

I tested adding a `UserWarning`, but it is simply overshadowed by the stack trace from the exception.

See also #243 #160

**Comment by prusnak** [comment]
Will be fixed via https://github.com/trezor/python-trezor/pull/245
