### ISSUE TITLE
Having some trouble with the helloworld and get_transport

### ISSUE THREAD

**Issue by nmfarshad** [trezor/python-trezor#253]
I am using a virtualenv with paython=python3 flag I am getting this error 
anyone please advice

Running using python3 connect.py
```
Traceback (most recent call last):
  File "connect.py", line 2, in <module>
    from trezorlib.transport import get_transport
ImportError: cannot import name 'get_transport'
```

**Comment by prusnak** [comment]
Works for me

**Comment by matejcik** [comment]
it seems you have an older version of trezorlib installed. try running `python setup.py install` in the virtualenv

**Comment by nmfarshad** [comment]
trezorctl command out put 
```
trezorctl version
0.9.0
```

**Comment by matejcik** [comment]
aha, you're using `helloworld.py` from master but using older library version.
you either need to find an older version of `helloworld.py`, or update the library to version from git

**Comment by nmfarshad** [comment]
upgraded the version and now 

```
(env) farshad@vb:~/tz$ trezorctl version
0.9.1
(env) farshad@vb:~/tz$ python3 connect.py
Traceback (most recent call last):
  File "connect.py", line 2, in <module>
    from trezorlib.transport import get_transport
ImportError: cannot import name 'get_transport'
```

**Comment by matejcik** [comment]
0.9.1 is not good enough
you need unreleased version from git -- or find an older `helloworld.py`
like this one from 0.9.1: https://github.com/trezor/python-trezor/blob/v0.9.1/tools/helloworld.py

**Comment by nmfarshad** [comment]
Got it I am referring to the master helloworld.py but my version is 0.9.1 
Thanks !
