### ISSUE TITLE
Trying to import proto_types

### ISSUE THREAD

**Issue by nmfarshad** [trezor/python-trezor#254]
I am using v0.9.1 and I couldn't import this module 
`import trezorlib.types_pb2 as proto_types`

getting error
```
import trezorlib.types_pb2 as proto_types
ImportError: No module named 'trezorlib.types_pb2'
```

I am trying to sign a tx following an example given in tools folder 
https://github.com/trezor/python-trezor/blob/v0.9.1/tools/signtest.py

**Comment by matejcik** [comment]
unfortunately, `signtest.py` has been broken for some time now and because of its complexity, it's unlikely to be fixed anytime soon.

I suggest instead looking at `trezorctl` and what it does when signing a transaction.
