### ISSUE TITLE
Segwit p2sh(p2wsh) multisig signing 

### ISSUE THREAD

**Issue by nmfarshad** [trezor/python-trezor#258]
How do I sign two inputs one is p2sh and the other one is p2sh(p2wsh) please advice ?

PS- I am using the python library v0.9.1 and trying to use **MultisigRedeemScriptType** and **client.sign_tx**

**Comment by prusnak** [comment]
Look in the multisig unittests, for example https://github.com/trezor/python-trezor/blob/master/trezorlib/tests/device_tests/test_multisig.py
