### ISSUE TITLE
Is it possible to use `sign_message` to sign a transaction?

### ISSUE THREAD

**Issue by cpastro** [trezor/python-trezor#259]
Hi, I'm sorry, but I have another question related to `sign_message`. Is it possible to use `sign_message` to sign a transaction? Actually I am using client.call(proto.SignMessage(...)) directly with the message in bytes.

I have a hash of a transaction that I created by hand and want to use `sign_message` to sign it, but the R and the S that are returned are different that the R and S that I get with `sign_tx`. The same result is returned everytime so I think Trezor is following RFC 6979 and I am 99.9% sure that I have constructed the serialized tx correctly, so is there any other explanation?

Thank you! 

Update: This is for a bitcoin testnet (non-segwit) transaction where I construct the transaction basically following this [bitcoin stack exchange answer](https://bitcoin.stackexchange.com/a/5241/82868). Are non-segwit transactions still constructed in this way?

**Comment by prusnak** [comment]
You cannot use sign_message to sign a transaction, because there is a
fixed prefix being added to the message before the signing to make it
impossible to accidentally sign a valid transaction.

**Comment by cpastro** [comment]
This explains everything. Thank you very much!
