### ISSUE TITLE
Include Trezor "message" parameter in: encrypt_keyvalue, decrypt_keyvalue

### ISSUE THREAD

**Issue by jcalfee** [trezor/python-trezor#264]
This looks like the main encrypt_keyvalue code:
https://github.com/trezor/python-trezor/blob/e656bbf0725ec7d9147d26cb5084ddff5370a16b/trezorlib/client.py#L830

I noticed it does not have the Trezor message.  In the Trezor API (and the trez project below), files were created with a specific message which becomes part of validation when decryption (the message, prompt booleans, iv must all match).  The Trezor encryption's depends on this message.  It can have a default but for the decryption that is important.

Original Trezor API call:
https://github.com/jcalfee/trez/blob/0cf71b6abf9d6e2e8fc460df38ad6efd6433a04a/trez-format.js#L90-L91

Can you please include the Trezor Message as part of your  encrypt_keyvalue and decrypt_keyvalue functions?

**Comment by prusnak** [comment]
There is no message field. Only key and value. Key is shown on the
display. In your Javascript code trezorMsg is the key, secret is
the value.
