### ISSUE TITLE
trezorctl: implement firmware_update for both T1 and T2

### ISSUE THREAD

**Issue by prusnak** [trezor/python-trezor#269]
`firmware_update` function should do the following:

1) use `connect().features.bootloader_mode` to check whether the device is in the bootloader mode first and throw an exception if not

2) use `connect().features.major_version` to determine whether we use T1 or T2

3) use `https://wallet.trezor.io/data/firmware/%d/releases.json` instead of `https://wallet.trezor.io/data/firmware/releases.json` for further processing

**Comment by matejcik** [comment]
@prusnak I'm sort of unhappy that for model `T`, the url says `2`.

could we support also `/firmware/T/releases.json` so that we could simply trust the device and use `features.model` directly without translation?

**Comment by matejcik** [comment]
for now we will use `features.major_version`
