### ISSUE TITLE
Load device command does not work with Trezor T

### ISSUE THREAD

**Issue by yura-pakhuchiy** [trezor/python-trezor#278]
`trezorctl load_device` does not work with T2. Tested with both physical device and emulator. Is there any alternative way (except actually entering seed using device's screen)?

**Comment by matejcik** [comment]
no. this only works with debug mode, there is no plan to have this in production firmware

**Comment by yura-pakhuchiy** [comment]
Found answer myself, documenting here in case somebody will be looking for this as well:
Create file `emu.config` in the root of the sources and add line `OPTLEVEL=0` there.

**Comment by matejcik** [comment]
this works for an older version of TT firmware. In current git master, you need to set `PYOPT=0`.

You can also run the emulator with this manually:
```sh
OPTLEVEL=0 ./emu.sh
PYOPT=0 ./emu.sh
```
