### ISSUE TITLE
Missing support directory

### ISSUE THREAD

**Issue by curiosity81** [trezor/python-trezor#280]
Hello,

if one follows the README.md for the Trezor T, then the support directory in trezorlib/tests is missing. However, in the current git snapshot, the directory is present.

I solved this as follows:
https://github.com/namecoin/electrum-nmc/issues/6

**Comment by matejcik** [comment]
oh. wellp. time for another point release.

FWIW this is fixed in current Electrum master: https://github.com/spesmilo/electrum/commit/208606beda445c243620727c68ad19b85e47ada2
