### ISSUE TITLE
"**Failed to find a TREZOR device.**"

### ISSUE THREAD

**Issue by gatineauio** [trezor/python-trezor#282]
Trying to run trezorctl on Raspberry PI 3 and I get "**Failed to find a TREZOR device.**"

I've added UDEV rules to be safe.  I'm running as the commands using sudo and have all the latest packages installed.  I've tested the device on another machine and it works just fine.

Unsure how to proceed.

**Comment by matejcik** [comment]
please post output of `trezorctl -v list`

Is this a Trezor One or Trezor T? If it's model One, you need `hidapi` libs, maybe you don't have these?

**Comment by gatineauio** [comment]
It is the original model One.

I get an error when running the command trezorctl -v list:
"Failed to import module hid: No module name 'hid'.

sudo pip3 install hidap i?

**Comment by gatineauio** [comment]
installing hidapi seemed to have resolved -- oddly it took over 20 minutes to install.

Thanks much.
Does it make sense to make the error more verbose? 

Again, thanks very much.  Awesome response time.

**Comment by matejcik** [comment]
Right now, only Trezor One needs the hidapi libs, and only on systems that don't have Trezor Bridge installed. And we expect to release a webusb upgrade to the T1 soon, so it won't need hidapi at all.
(that is why hidapi is now optional, and that is probably why you didn't have it)

It might make sense to put an explanatory line if no device is found *and* hid libraries are missing, but it's low priority.
