### ISSUE TITLE
detect old versions of TREZOR Firmware

### ISSUE THREAD

**Issue by prusnak** [trezor/python-trezor#283]
We should hardcode the minimum version of supported TREZOR firmware in trezorlib. When working with older than minimum version we should somehow indicate this to upper layers (trezorctl, electrum) so they can show a warning and instruct user to perform a firmware update.

Mininimum version is the last version that has "required: true:" in releases.json ([T1](https://wallet.trezor.io/data/firmware/1/releases.json) and [T2](https://wallet.trezor.io/data/firmware/2/releases.json))

**Comment by matejcik** [comment]
implemented in https://github.com/trezor/python-trezor/commit/d9e5fd2682f68cab09bd7dcf1486cf23368785b5
