### ISSUE TITLE
Missed backslash ('/') in the URL address

### ISSUE THREAD

**Issue by idimon4uk** [trezor/python-trezor#288]
Hi Trezor Team,
We've found some issues in the method "get_url" in trezorlib/tx_api.py . It is connected with the appending of URL address. There is missing '/' between "url" and "tx". As a result, we have an incorrect URL when trying to append bitcore url "tx" and "txidso.
Please find the screenshots attached:
Also, we ‘ve prepared a quick fix for this issue. You can find it in our repository with the following link: https://github.com/idimon4uk/python-trezor/commit/a6fa86f3fa9f70f214458e6e7e5400df34e6ed28
![image](https://user-images.githubusercontent.com/16037887/42778863-2c978e7a-8947-11e8-911a-76b919967c12.png)

**Comment by matejcik** [comment]
this is now fixed
