### ISSUE TITLE
Cardano support

### ISSUE THREAD

**Issue by tsusanka** [trezor/python-trezor#295]
Since Cardano will be supported by Trezor T, we want python-trezor to support it as well?

Somewhat connected to https://github.com/trezor/trezor-core/issues/309

**Comment by ddeath** [comment]
@tsusanka Sure we will add them. Just want to ask what about tests in trezor-core? Are they needed or not? https://github.com/trezor/trezor-core/blob/master/tests/test_apps.cardano.address.py

**Comment by tsusanka** [comment]
Yes. Both are. Basically we have two types of tests:

- unit tests, directly included in trezor-core/trezor-mcu repositories, which is exactly what you are referencing to
- device tests (aka integration tests), which are part of the python-trezor repository and are "trezor model independent". In other words those are tests that can be run against both Trezor One and Trezor T. They actually send protobuf messages to the device and expect some other protobuf messages with results

**Comment by matejcik** [comment]
Just a note: please keep in line with Ripple (#286) style, as opposed to Lisk/Stellar.
I'm currently converting the whole codebase to the new style (see #276) and I won't be accepting PRs that add methods to `client.py`

**Comment by ddeath** [comment]
@tsusanka added tests in #300

**Comment by ddeath** [comment]
@tsusanka same here, test are merged so this is ready for close i guess?

**Comment by tsusanka** [comment]
Yes, thank you!
