### ISSUE TITLE
Invald coin name

### ISSUE THREAD

**Issue by rockandruby** [trezor/python-trezor#296]
Installed latest trezor on Ubuntu 16.04. Use trezor one. When I try to sign multisig transaction I get 'Invalid coin name'

**Comment by prusnak** [comment]
What exactly you are doing? Post the screenshot and also tell us the firmware version.

**Comment by rockandruby** [comment]
I try to sign multisig transaction for dash testnet and when I try to sign by trezor I get http://joxi.ru/xAeO6w0up6Db9m  I use trezord 2.0.19 version

**Comment by prusnak** [comment]
You need firmware at least 1.6.2 to use Dash Testnet. Please update the firmware.

**Comment by rockandruby** [comment]
@prusnak how can I use 1.6.2 if your python-trezor latest version is 0.10.2 from 2018-06-21 or what firmware you were talking about?? I use almost all newest libs, electrum-dash, trezor bridge etc...

**Comment by matejcik** [comment]
you need Trezor firmware version 1.6.2
Go to wallet.trezor.io to update.

(You could also update with `trezorctl firmware_update`. But note that this update **will wipe your device**. The wallet webpage knows this and will warn you. Trezorctl won't.)

**Comment by rockandruby** [comment]
@matejcik I already use 1.6.2

**Comment by prusnak** [comment]
Seems like a bug in Electrum-DASH, see https://github.com/dashpay/electrum-dash/blob/master/plugins/trezor/plugin.py#L147-L148

**Comment by matejcik** [comment]
...i mean, "invalid coin name" doesn't make sense even then, seeing as both "Bitcoin" and "Testnet" are valid names.
But yes, there is definitely an Electrum-DASH bug. We can investigate later, if it turns out that there is another problem on our side.

**Comment by rockandruby** [comment]
@prusnak @matejcik thanks guys!
