### ISSUE TITLE
 AttributeError: 'BridgeTransport' object has no attribute 'find_debug'

### ISSUE THREAD

**Issue by ddeath** [trezor/python-trezor#299]
When I am running device_tests I often get this error:

` AttributeError: 'BridgeTransport' object has no attribute 'find_debug'`

All test fails on that error and I need rerun the test 5-10 times until it does not errors anymore.

Any idea how to prevent this from happening?

I am running it on python3, linux

**Comment by prusnak** [comment]
Bridge does not provide debug interface. Turn off the bridge do python-
trezor will access Trezor directly.

Also make sure you run `PYOPT=0 ./emu.sh` so the emulator runs in debug
mode. (Careful: This will erase emulator storage on each start).

@matejcik if this is not documented somewhere already, can you put this
somewhere in the python-trezor docs?

**Comment by ddeath** [comment]
It is kind of documented here: https://github.com/trezor/trezor-core/blob/9e16eb4122cc5416dec1dee4f7646cb7dba358a8/docs/testing.md but it would be nice have it also in this repo.

But there is no mention that trezord-go can "interfere" with running tests.

Thanks for explanation
