### ISSUE TITLE
Why is the v1 protocol forced for HID devices?

### ISSUE THREAD

**Issue by stevenroose** [trezor/python-trezor#320]
https://github.com/trezor/python-trezor/blob/master/trezorlib/transport/hid.py#L73

**Comment by matejcik** [comment]
um, probably because Trezor One (_the_ HID device) only supports V1? :)

**Comment by matejcik** [comment]
...actually, T2 also only supports V1, V2 is unfinished, what you see is a stub of "smart decision" code that isn't actually good for anything right now.
