### ISSUE TITLE
Update Error

### ISSUE THREAD

**Issue by Rspigler** [trezor/python-trezor#322]
I run Fedora 28 (Freed-ora more specifically) on my full node machine.  Running `sudo dnf upgrade` today I noticed a python3-trezor update available.  However, I got the following error:

> file /usr/lib/udev/rules.d/51-trezor.rules from install of python3-trezor-0.10.2 conflicts with file from package trezor-common-0-0.3

Removing python3-trezor as well as trezor-common and reinstalling results in same error

**Comment by prusnak** [comment]
This is a downstream packaging error. Open the issue in Fedora bug tracker.
