### ISSUE TITLE
zcash sapling not supported in 0.10.2

### ISSUE THREAD

**Issue by wo01** [trezor/python-trezor#333]
Zcash and its clone coins using version_group_id cannot use python-trezor 0.10.2.
Therefore, new release is needed for those coins.

When will you release the next release?

**Comment by matejcik** [comment]
the python-trezor API is being reworked at the moment, I expect a release within two weeks.

for the zcash thing though, it might make sense to do an intermediate 0.10.3 release

**Comment by matejcik** [comment]
python-trezor 0.11 is now released
