### ISSUE TITLE
Travis CL seems to be failing 10.x PRs due to Py3.4 requirements

### ISSUE THREAD

**Issue by brianddk** [trezor/python-trezor#345]
Attempted a simple PR against 10.x but it seems to be failing the Python 3.3 tests due to Python 3.4 requirements by the 10.x branch.

https://github.com/trezor/python-trezor/pull/344

Possible bug in automation config?

**Comment by matejcik** [comment]
Well, the ecosystem moved away from python 3.3 and it's been too much pain to keep the py3.3 travis check running, that's the reason we dropped support.

Anyway, I just released 0.11.0, we probably won't maintain the 0.10.x branch anymore, so closing this for now. If we need to resurrect that branch, we'll also drop the py3.3 build.
