### ISSUE TITLE
Is there a way to restore seed words in scrambled order?

### ISSUE THREAD

**Issue by cculianu** [trezor/python-trezor#373]
Hi,

Electron Cash dev here.  I pass the recover type Scrambled to the lib -- but the seed recovery process still asks for the words in sequential order (1, 2, 3... etc).

Is there a way to make the recovery process actually use a scrambled word order like the website does?

I'm on a Model T and on the little white Trezor.  Both have the same problem using trezorlib.

**Comment by prusnak** [comment]
Show us your code, please

**Comment by cculianu** [comment]
Wait -- so it's supposed to work?  Maybe there is a bug in the code then.  This is the Electron Cash project -- the codebase to the trezor support is huge and contorted.  Here where you can look:

https://github.com/Electron-Cash/Electron-Cash/blob/master/plugins/trezor/clientbase.py#L222

Electrum has the same problem though.

https://github.com/spesmilo/electrum/tree/master/electrum/plugins/trezor

**Comment by cculianu** [comment]
I even hard-coded 'ScrambledWords' in there here to test:

```
    def recover_device(self, recovery_type, *args, **kwargs):
        input_callback = self.mnemonic_callback(recovery_type)
        with self.run_flow():
            kwargs.pop('type', None)
            print("HARD CODED RECOVERY TYPE", RecoveryDeviceType.ScrambledWords)
            return trezorlib.device.recover(
                self.client,
                *args,
                input_callback=input_callback,
                type=RecoveryDeviceType.ScrambledWords,
                **kwargs)
```

And it's still not scrambled...

**Comment by cculianu** [comment]
FYI: I'm using trezorlib 0.11.2 release..

**Comment by cculianu** [comment]
Update: This works perfectly on a Trezor One (the little white one) but not on a Model T.

**Comment by prusnak** [comment]
On Model T you enter the words on the device. No need to scramble them.

**Comment by cculianu** [comment]
Gotcha. Thanks.
