### ISSUE TITLE
python-trezor 0.11.3 released on PyPI but not tagged here

### ISSUE THREAD

**Issue by SomberNight** [trezor/python-trezor#379]
It seems 0.11.3 is available on PyPI: https://pypi.org/project/trezor/0.11.3/

but changelog in git repo still says 0.11.3 is unreleased: https://github.com/trezor/python-trezor/blob/2813522b05cef4e0e545a101f8b3559a3183b45b/CHANGELOG.md

and latest tag is v0.11.3
https://github.com/trezor/python-trezor/tags

Could you please tag the commit that has been released on PyPI?

**Comment by matejcik** [comment]
development in this repository is frozen and continues in trezor-firmware:
https://github.com/trezor/trezor-firmware/blob/master/python/CHANGELOG.md
https://github.com/trezor/trezor-firmware/tags

**Comment by prusnak** [comment]
@matejcik Shouldn't we make this repo Archived then? (after moving issues to trezor-firmware)

**Comment by matejcik** [comment]
yes. i moved all the issues, please archive the repo and update description to point to the monorepo.
(maybe we could push a README too?)
