### ISSUE TITLE
how should change_pin behave?

### ISSUE THREAD

**Issue by cyphunk** [trezor/python-trezor#4]
change_pin and reset_device -p are not accepting my pins. I tried pin1=1234 pin2=1234 and pin1=screenpos_1234 pin2=new_screenpos_1234. Also tried with the assumption of offset by 0. No luck. any advice?

**Comment by reiven** [comment]
hello @prusnak , it will be a good idea to add the information about how to enter "scrambled pin" in the main readme, so you dont have to browse closed issues to find that information :)

**Comment by prusnak** [comment]
@reiven Agreed. Will you do it, please?
