### ISSUE TITLE
python setup.by install error on osx mavericks

### ISSUE THREAD

**Issue by tphyahoo** [trezor/python-trezor#41]
Installed /Library/Python/2.7/site-packages/trezor-0.6.5-py2.7.egg
Processing dependencies for trezor==0.6.5
Searching for hidapi>=0.7.99
Reading http://pypi.python.org/simple/hidapi/
Download error: [Errno 8] nodename nor servname provided, or not known -- Some packages may not be found!
Couldn't find index page for 'hidapi' (maybe misspelled?)

I did brew install hidapi and

brew install hidapi
Warning: hidapi-0.8.0-rc1 already installed

but that didn't fix the problem.

**Comment by tphyahoo** [comment]
downloaded 

https://pypi.python.org/packages/source/h/hidapi/hi
dapi-0.7.99-6.tar.gz

and untarred and did python setup.py install

and that seems to have unkinked the initial install

**Comment by prusnak** [comment]
Seems like a temporal network issue. Closing
