### ISSUE TITLE
allow core entropy entry through pin pad

### ISSUE THREAD

**Issue by tphyahoo** [trezor/python-trezor#44]
Rather than trust host computer for source of entropy, allow user to generate entropy via alternative means (eg diceware, flipping coins, or however).

The entropy would be entered via the scrambled pin mechanism.  If we just use digits 1-8, 256 bits would be 32 entries, or 128 bits would be 16.  A bit of a pain, but not too bad.  The entropy entry could be repeated to ensure no mistakes.

(For stylepoints, trezor could add a "hexadecimal pin pad" to slyly hint that only 3l1te experts should be using this feature.)

After the entropy entry the 3*x word passphrase would be calculated and displayed to user as usual.  The user could can now either 

-- throw away the entropy seed, and do future restores with current mechanism
-- or keep the entropy seed, and do future restores with extra secure mechanism of re-entering same entropy via keypad, so even if host computer is compromised the original entropy is maintained, and we don't leak down to 24 factorial, or however many if an attacker gains a scrambled word list.

As a side note on naming, I would refer to "core entropy seed" described above, versus "stretched entropy seed" which is encoded by the pass phrase that is usually referred to as the seed.

For everyone who has ever wondered if /dev/random is back doored on their system, the trezor now presents an irresistible value proposition.

**Comment by prusnak** [comment]
Just use the `load_device` feature with `skip-checksum` option such as

`./trezorctl load_device -m 123456  -s`

where 123456 is the dice sequence or HTTHTTTHTTH for coin toss (maximum length of the sequence is 240 chars! IIRC). Needless to say this requires an uncompromised computer. If you want to perform this on TREZOR this might be also an option but such request belong to https://github.com/trezor/trezor-mcu tracker, not here.

**Comment by tphyahoo** [comment]
Yes, it's important to be able to do this safely on an uncompromised computer.  

I wasn't sure which tracker to use, thanks for the pointer, resubmitting.

Cheers.
