### ISSUE TITLE
static methods should be so marked

### ISSUE THREAD

**Issue by kyuupichan** [trezor/python-trezor#48]
e.g. expand_path() in the ProtocolMixin.  These do not need an instance.

**Comment by prusnak** [comment]
If you think this is worth pursuing please send a pull request.

**Comment by kyuupichan** [comment]
An example of why it's useful: your tx_api callback does not provide a self argument, because one is not needed.  The problem is that if that tx_api wants to call expand_path (which it does), it suddenly needs a self argument to call it on.  That is not good.

**Comment by prusnak** [comment]
Do you have a capacity to prepare the pull request?

**Comment by kyuupichan** [comment]
Fair enough.  I think it should work; I can't test it though.  Electrum now uses a modified copy of this code; once KeepKey and Trezor libraries have supported a static one for a while I'd be happy to remove it and use the library one.

**Comment by prusnak** [comment]
I merged the PR and will close this issue. If there are more, feel free to send another PR. Thank you!
