### ISSUE TITLE
protobuf version fallback

### ISSUE THREAD

**Issue by ulrichard** [trezor/python-trezor#50]
When using python-trezor 0.6.10 on trisquel belenos, I get the following error:

File "/usr/lib/python2.7/dist-packages/trezorlib/client.py", line 7, in <module>
    import mapping
  File "/usr/lib/python2.7/dist-packages/trezorlib/mapping.py", line 1, in <module>
    import messages_pb2 as proto
  File "/usr/lib/python2.7/dist-packages/trezorlib/messages_pb2.py", line 10, in <module>
    from google.protobuf import symbol_database as _symbol_database
ImportError: cannot import name symbol_database

The packaged version of protobuf is:  2.5.0-9ubuntu1

Is there a possible fallback other than installing protobuf from pip? 
I prefer to have as much as possible from apt.
That would mean I would have to maintain a newer version of protobuf in my ppa. 

If the symbol_database functionality is not always needed, would graceful degradation be an option?

**Comment by prusnak** [comment]
If you prepare the patch I might consider merging it. But recent versions of distros already ship protobuf 2.6.x, so I am not sure if it's worth the hassle.

**Comment by ulrichard** [comment]
Backporting protobuf for the ppa was easier than I thought.
https://launchpad.net/~richi-paraeasy/+archive/ubuntu/bitcoin

**Comment by prusnak** [comment]
There you go
