### ISSUE TITLE
v.0.6.10 problems connecting

### ISSUE THREAD

**Issue by ELM4Ever** [trezor/python-trezor#51]
Just updated my python-trezor library from 0.6.6 to 0.6.10 - then started to have communication problem using Electrum (version 2.5.4). 

 File "/Library/Python/2.7/site-packages/trezor-0.6.10-py2.7.egg/trezorlib/transport_hid.py", line 54, in enumerate
    raise Exception("Unknown USB interface number: %d" % interface_number)
Exception: Unknown USB interface number: -1

Same error comes up when using the example code in the repository Readme file.  Therefore, problem is not with Electrum.

Reverted back to v.0.6.6 and it worked again.

**Comment by prusnak** [comment]
Fucking OS X. Fixed in 915cf0099e1783e097db0b19bc8e847d5023947c and released as 0.6.11

**Comment by ELM4Ever** [comment]
Thanks.  It works now.

BTW:  v0.6.11 is not compatible with protobuf v3.0.0.  I understand that the latest stable version is 2.6.1, but if left unspecified in a setup.py file, protobuf will update to 3.0.0 (which is the case for Electrum).   I have asked Electrum to force the download to 2.6.1, but you may also want to have a look at the issue with 3.0.0.

**Comment by ELM4Ever** [comment]
Just to let you know.  python-Trezor 0.6.11 works with Electrum 2.5.4, but not version 2.6 (latest github head).  They are looking at this issue.

**Comment by prusnak** [comment]
python-trezor never worked with protobuf 3.x.

There is a requirement on version 'protobuf==2.6.1' in setup.py of python-
trezorgggggg




--
Best Regards / S pozdravom,
 
Pavol Rusnak <stick@gk2.sk>
 
 
On Mon, Jan 18, 2016, at 03:01 AM, ELM4Ever wrote:
> Just to let you know.  python-Trezor 0.6.11 works with Electrum 2.5.4, but not version 2.6 (latest github head).  They are looking at this issue.


> —
> Reply to this email directly or view it on GitHub[1]. 


>  
 


Links:

  1. https://github.com/trezor/python-trezor/issues/51#issuecomment-172407099

**Comment by ELM4Ever** [comment]
Latest changes made to Electrum 2.6, combined to python-trezor 0.6.11 now work well (OSX).

Thanks.
