### ISSUE TITLE
Is it possible to force trezor to watch specific path?

### ISSUE THREAD

**Issue by iYalovoy** [trezor/python-trezor#54]
Might wrong place to ask, but can't find one anyway.
Let's say I want my trezor to watch path "44'/0'/0'/0/9999", when all previous addresses not used?
Is it possible with this api? How can I then send money from this address?

**Comment by prusnak** [comment]
It is possible to use trezorctl to get the address at this position:

```
trezorctl get_public_node -n "m/44'/0'/0'/0/9999"
```

Howerver spending coins is quite complicated and not possible via the command line interface at the moment. See [signtx testcase](https://github.com/trezor/python-trezor/blob/master/tests/test_msg_signtx.py) for examples how to use `client.sign_tx()` method from the Python code.

**Comment by iYalovoy** [comment]
Thanks for response. Quickly looked through the code, looks complicated ;-) I have no problem getting actual address, problem is how to spend these money, because my trezor website is not going to see them. I understand that this is more an issue with my trezor service, rather than api itself, but would be great if there is any simple method to spend/check coins from any particular address.

**Comment by slush0** [comment]
You're correct, it is out of responsibility of this library. I'm sorry for your issue, please contact support on support@bitcointrezor.com for help with your wallet.
