### ISSUE TITLE
Add Python3 support

### ISSUE THREAD

**Issue by slush0** [trezor/python-trezor#56]
There's WIP in branch named "python3". Unfortunately I was unable to compile messages_pb2.py and types_pb2.py with python3 syntax yet, which looks like the last obstacle to get it running.

**Comment by slush0** [comment]
Basic things should work since fe29085, although not everything is 100% (unit tests).

**Comment by prusnak** [comment]
More of the stuff added. It seems the best way would be to rewrite all `str`/`unicode`/`bytes` + conversions mess using `bytearray`. :-/

**Comment by prusnak** [comment]
Closing this issue as python3 is merged into master and most of the stuff works. Therefore there is no need to have metaissue like this floating around.
