### ISSUE TITLE
Windows instalation - error

### ISSUE THREAD

**Issue by Comodore125** [trezor/python-trezor#58]
Error: package diectory 'trezorlib' does not exist. 

I made all previous steps that were required. 

![shit](https://cloud.githubusercontent.com/assets/6156234/15307335/474cdc0a-1bd2-11e6-9550-af7d666d9cc5.JPG)

**Comment by prusnak** [comment]
Does installing via pip work?

**Comment by prusnak** [comment]
Also I guess you need to be in the python-trezor directory.

So you should run the following:

```
C:\python27/python.exe setup.py install
```

**Comment by prusnak** [comment]
Reopen of the issue still persists.

**Comment by Comodore125** [comment]
There should be a new version of dash-electrum soon so I will not bother with this unless this problem will be in new version as well.
