### ISSUE TITLE
Rewrite all str/unicode/bytes usage + conversions mess using bytearray

### ISSUE THREAD

**Issue by prusnak** [trezor/python-trezor#59]
That would be probably the best way how to achieve Python 2 and Python 3 compatibility without going completely insane.

**Comment by saleemrashid** [comment]
`trezorctl` seems to work (only?) with Python 3 now so this can probably be closed

**Comment by prusnak** [comment]
Well, there is still some cleanup to do, but most of the problems were solved already, let's close this. Whole package should work for both Py2 and Py3. If it does not work for either it is a bug which should be addressed.
