### ISSUE TITLE
Bug on mac

### ISSUE THREAD

**Issue by runn1ng** [trezor/python-trezor#70]
With the new firmware, python-trezor is not usable on mac, because we are using unpatched hidapi

see

https://github.com/signal11/hidapi/pull/288

so neither can users use electrum (and electrum dash, etc).

Once the hidapi is patched everything should work again

**Comment by runn1ng** [comment]
This should be fixed now, since pypi hidapi is using our patched hidapi fork. Closing this issue.

**Comment by meeDamian** [comment]
@runn1ng I think the bootloader mode visibility might still be broken on macOS because of that; discussed before [here](https://gitter.im/trezor/community?at=585c1382af6b364a29e5aef2).
