### ISSUE TITLE
 Include a license file in the tarball

### ISSUE THREAD

**Issue by hegjon** [trezor/python-trezor#81]
The tarball hosted on Python Package Index is used as the source for repackage python-trezor as a RPM package in Fedora.

It would make it easier to redistribute python-trezor if the tarball included a license file.

See https://fedoraproject.org/wiki/Packaging:LicensingGuidelines?rd=Packaging/LicensingGuidelines#License_Text for more details

**Comment by prusnak** [comment]
Fixed via #82
