### ISSUE TITLE
Include a proper license header in source files

### ISSUE THREAD

**Issue by hegjon** [trezor/python-trezor#84]
It would make it easier to redistribute python-trezor in Fedora[1] if each source file contains a license header. The only file that have license header is trezor-0.7.7/trezorlib/protobuf_json.py, which is licensed BSD. Can you confirm that the rest of the files are licensed LGPLv3?

Check https://bugzilla.redhat.com/show_bug.cgi?id=1398340#c3 and  for details.

[1] https://fedoraproject.org/wiki/Packaging:LicensingGuidelines?rd=Packaging/LicensingGuidelines#License_Clarification

**Comment by prusnak** [comment]
Yes, the rest is LGPLv3.

**Comment by hegjon** [comment]
Thanks for your confirmation

**Comment by prusnak** [comment]
Added headers in https://github.com/trezor/python-trezor/commit/0bba09274169bb93bac37803313ccb8656f4ae68

Feel free to reopen when something else is needed.

**Comment by hegjon** [comment]
Thanks for the quick fix
