### ISSUE TITLE
Multisig examples?

### ISSUE THREAD

**Issue by reiven** [trezor/python-trezor#91]
It will be great to have some examples or a guide on how to 'be part' of a multisig address and how to sign a multisig transaction with this lib

Thanks

**Comment by prusnak** [comment]
Check unit tests here:
* https://github.com/trezor/python-trezor/blob/master/tests/device_tests/test_multisig.py
* https://github.com/trezor/python-trezor/blob/master/tests/device_tests/test_multisig_change.py
