### ISSUE TITLE
Include a release-notes or changelog file

### ISSUE THREAD

**Issue by hegjon** [trezor/python-trezor#94]
It would help users and packagers of Linux distributions if there is a release-notes or changelog file describing the changes done in a release. Example: https://github.com/spesmilo/electrum/blob/master/RELEASE-NOTES

**Comment by matejcik** [comment]
I added a changelog from 0.9.0 to 0.9.1. Still trying to figure out how best to autogenerate it.

**Comment by matejcik** [comment]
changelog is now formatted according to keep-a-changelog.

will have to keep it manually, but that is probably a better solution anyway.
